### ISSUE TITLE
Will vehicles from the Arma 3 Creator DLC be added: Reaction Forces?

### ISSUE THREAD

**Issue by ZERONIGT** [Gamer-Dad/warlordsredux.altis#234]
Yesterday, a new expansion for Arma 3 was released, adding a lot of vehicles. The question is, will this equipment be available in Warlords mode?

**Comment by notMONGCHAW** [comment]
The only issue as of right now would be the fact that we need to see if those are accessible outside DLC Owners because as most of the vehicles and gadgets in the game (Spectrum Device, Pelican Drone, Stealth Shikhra) you can buy and and have them in game you wont be able to access them as that is restricted by BI.
But we are not completely removing the idea or the plan we might have a proper response to it soon ™️

**Comment by ZERONIGT** [comment]
> The only issue as of right now would be the fact that we need to see if those are accessible outside DLC Owners because as most of the vehicles and gadgets in the game (Spectrum Device, Pelican Drone, Stealth Shikhra) you can buy and and have them in game you wont be able to access them as that is restricted by BI. But we are not completely removing the idea or the plan we might have a proper response to it soon ™️

It would be very cool if you could implement this)
